baseurl                 = "https://blog.asterism.xyz/"
DefaultContentLanguage  = "ja-jp"
hasCJKLanguage = true
title                   = "blog.asterism.xyz"
theme                   = "hugo-future-imperfect-slim"
preserveTaxonomyNames   = true
paginate                = 5
disqusShortname         = "blog-asterism-xyz"
comment                 = false
googleAnalytics         = "UA-73782110-3"
pluralizeListTitles     = false
disableLanguages        = [""]
enableRobotsTXT = true
canonifyURLs = true

[params]
  mainSections = ["blog", "post"]
  # Loads CSS and JavaScript files. The variable is an array so that you can load
  # multiple/additional files if necessary. The standard theme files can be loaded
  # by adding the value, "default". Default includes the add-on.css and and-on.js.
  # Example: ["default", "/path/to/file"]
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  # Sets options for highlight.js
  highlightjs           = false
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  # Sets where "View More Posts" links to
  viewMorePostsLink     = "/posts/"
  # Activate Estimated Reading Times, which appear in the post headers
  readingTime           = false
  # Sets which Social Share links appear in posts.
  # Options are twitter, facebook, reddit, linkedin, pinterest, email
  socialShare           = []

  images = ["img/main/logo.png"]

  [params.meta]
    # Sets the meta tag description
    description         = "aries@mstdn.asterism.xyzのブログ"
    # Sets the meta tag author
    author              = "aries@mstdn.asterism.xyz"
    # If you would like to add more comprehensive favicon support passed root
    # directory favicon.ico, utlize this funtion. It is recommened to use
    # https://realfavicongenerator.net to generate your icons as that is the basis
    # for the theme's naming.
    favicon             = true
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#da532c" # Copy from the https://realfavicongenerator.net
    iOSColor            = "#ffffff" # Copy from the https://realfavicongenerator.net

  [params.header]
    # Sets the navbarTitle that appears in the top left of the navigation bar
    navbarTitle         = "blog.asterism.xyz"
    # Sets navbarTitle to match the section of the website
    dynamicTitles       = false
    searchMenu          = false
    shareMenu           = false
    languageMenu        = false

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
  [params.intro]
    header                = "aries"
    paragraph             = "ITインフラエンジニア<br><a href='https://www.asterism.xyz'>My central page.</a>"
    rssIntro              = true
    socialIntro           = true

    # This appears at the top of the sidebar above params.intro.header.
    # A width of less than 100px is recommended from a design perspective.
    [params.intro.pic]
      src                 = "/img/main/logo.png"
      # Masks image in a certain shape. Supported are circle, triangle, diamond, and hexagon.
      shape               = "circle"
      width               = "128"
      alt                 = "icon"

  [params.sidebar]
    about               = "都内某所で自社の情シスとかやってます。<br>Server, Network, Security, Windows, Linux, vSphere, AWS, ConoHa"
    # Sets the number of recent posts to show in the sidebar. The default value is 5.
    postAmount          = 3
    # set to show or to hide categories in the sidebar
    categories          = true
    # Sets Categories to sort by number of posts instead of alphabetical
    categoriesByCount   = true

  [params.footer]
    # Sets RSS icons to appear on the sidebar with the social media buttons
    rssFooter           = false
    # Sets Social Media icons to appear on the sidebar
    socialFooter        = false

  # Disqus will take priority over Staticman (github.com/eduardoboucas/staticman)
  # due to its ease of use. Feel free to check out both and decide which you would
  # prefer to use. See Staticman.yml for additional settings.
  [params.staticman]
    # Sets Statiman to be active
    staticman           = false
    # Sets the location for Staticman to connect to
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      recaptcha         = false
      siteKey           = "" # Site Key
      encryptedKey      = ""

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item
  [[menu.main]]
    name              = "Home"
    url               = "/"
    identifier        = "home"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    url               = "/about/"
    identifier        = "about"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Posts"
    url               = "/posts/"
    identifier        = "posts"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    url               = "/categories/"
    identifier        = "categories"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Tags"
    url               = "/tags/"
    identifier        = "tags"
    pre               = "<i class='fas fa-folder'></i>"
    weight            = 6

[Languages]
  # Each language has its own menu.
  [Languages.ja-jp]
    languageCode        = "ja-jp"
    LanguageName        = "Japanese"
    weight              = 1

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github                = "orlea"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = ""
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = "aries_hituzi"
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = "aries_asterism"
  mastodon              = "mstdn.asterism.xyz/@aries"
  # Email
  email                 = ""
